version: "3.5"
services:
  influx:
    image: "influxdb:alpine"
    restart: unless-stopped
    # ports:
    #   - 8086:8086
    #   - 8088:8088
    environment:
      TZ: Europe/Moscow
    volumes:
      - influx-data:/var/lib/influxdb:rw

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - influx
    ports:
      - 3000:3000
    environment:
      TZ: Europe/Moscow
    # GF_PATHS_DATA='/var/lib/grafana' is not writable.
    # volumes:
    #   - /var/docker/Data/grafana:/var/lib/grafana:rw

  telegraf:
    # https://hub.docker.com/_/telegraf
    image: "telegraf:alpine"
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      HOST_ETC: /rootfs/etc
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_VAR: /rootfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
    extra_hosts:
      - "influxdb:influx"
    hostname: localhost
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - telegraf-logs:/var/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro

volumes:
  influx-data:
  telegraf-logs:
